# Codecov configuration
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, flags, components, tree, footer"
  behavior: default
  require_base: no
  require_changes: no
  require_head: yes
  hide_project_coverage: no

flags:
  unittests:
    paths:
      - rate-limiter-core/src/main/kotlin/
      - rate-limiter-spring-boot-starter/src/main/kotlin/
      - rate-limiter-app/src/main/kotlin/
    carryforward: true
